name: Post Deployment Health Check
on:
  workflow_run:
    workflows:
      - "Terraform Deployment"
    types:
      - completed

jobs:
  health_check:
    name: Post Deployment Health Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps: 
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: "https://tm.abdiyasirthreatcomposer.co.uk/health|http://tm.abdiyasirthreatcomposer.co.uk/health"
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
